### ISSUE TITLE
php-client throws non-oss exceptions

### ISSUE THREAD

**Issue by a4i** [jaeksoft/opensearchserver-php-client#48]
I get some Buzz\Exception\RequestException when the php client cannot connect to OSS (maintenance period, ie)

```
Exception from line 29 of ossphp/vendor/kriswallsmith/buzz/lib/Buzz/Client/Curl.php:
Failed to connect to localhost port 8080: Connection refused
```

Couldn't this be an OpenSearchServer exception ? I think it would be better for api stability to handle exceptions coming from client/oss dialog

regards

**Comment by AlexandreToyer** [comment]
Hi,

Thank you, I added some custom Exception for this error.

Alexandre
