### ISSUE TITLE
add getter to access OpenSearchServer\Document\Document fields

### ISSUE THREAD

**Issue by a4i** [jaeksoft/opensearchserver-php-client#49]
It would be great to have fields accessor in OpenSearchServer\Document\Document.

We need this to inspect document content while processing exceptions (and to save document unique field for future processing, for example)
No way to access the "fields" protected property for now.

Regards

**Comment by a4i** [comment]
Something like this :
```
	public function getField($fieldName) {
		if(empty($fieldName)) {
			throw new \InvalidArgumentException('Please provide a fieldname');
		}
		$values = array();
		array_map( function ($f) use (&$values, $fieldName) {
			if ( $f['name']===$fieldName) {
				array_push($values, $f["value"]);
			}
		}, $this->fields);
		return $values;
	}
```

**Comment by AlexandreToyer** [comment]
Hi,

Thank you, I added some code in class Document (I used a foreach instead of array_map).

Alexandre
