### ISSUE TITLE
Paging of results

### ISSUE THREAD

**Issue by AlienDave** [jaeksoft/opensearchserver-php-client#68]
In OSS PHP's "previous version" documentation, it talks about pagination of results. 
Why is this absent from the current version? 
Or, if it isn't, where's the documentation on how to use it?

**Comment by arjunkariyadan** [comment]
This is still available on the current version. You can use start() and rows() method in the request object to do the pagination.

$request = new OpenSearchServer\Search\Field\Search();
$request->index('index_name')
        //set some search fields
        ->searchFields(array('content', 'url'))
        ->start(0)
        ->rows(20)
        //set a specific different search field with Term & Phrase, term boost = 5 and phrase boost = 10
        ->searchField('title', OpenSearchServer\Search\Field\Search::SEARCH_MODE_TERM_AND_PHRASE, 5, 10)
$results = $oss_api->submit($request);
