### ISSUE TITLE
stored value in create a field method

### ISSUE THREAD

**Issue by muratti66** [jaeksoft/opensearchserver-php-client#69]
Hi 
stored value keys "true" or "false" typed in your document
this is not working
I've tried as, its working : (**->stored('YES')**)
`$request = new OpenSearchServer\Field\Create();
$request->index('index_name')
        ->name('titleStandard')
        ->indexed(true)
        ->analyzer('StandardAnalyzer')
        ->stored('YES')
        ->copyOf('title');
$response = $oss_api->submit($request)`

**Comment by emmanuel-keller** [comment]
Hi, we just made a fix by allowing both textual and boolean parameter (as we did for the indexed property). The main reason is that 'stored' should also support 'COMPRESSED' value.

We just updated the master and the 3.0 branch, can you check that ? If it will be fixed we will create a new tag.
